sudo: false
language: node_js
node_js:
  - "5"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint:fix
  - npm run test
  - npm run check-coverage

after_success:
  - npm run coveralls
